<a href="https://colab.research.google.com/github/itsZENR/LASSO_Ridge_ElasticNet_Polynom/blob/main/LASSO_Ridge_ElasticNet_Polynom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Библиотеки
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt 
import seaborn as sns

In [ ]:
url = '/content/diabetes.csv'
df = pd.read_csv(url)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
X = df[['SkinThickness', 'BMI']]
X

     SkinThickness   BMI
0               35  33.6
1               29  26.6
2                0  23.3
3               23  28.1
4               35  43.1
..             ...   ...
763             48  32.9
764             27  36.8
765             23  26.2
766              0  30.1
767             31  30.4

[768 rows x 2 columns]

In [ ]:
y = df[['Insulin']]
y

     Insulin
0          0
1          0
2          0
3         94
4        168
..       ...
763      180
764        0
765      112
766        0
767        0

[768 rows x 1 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25,random_state=1)

print(np.shape(X_train))
print(np.shape(y_train))

print(np.shape(X_test))
print(np.shape(y_test))

(576, 2)
(576, 1)
(192, 2)
(192, 1)

In [ ]:
# LASSO регрессия
from sklearn.linear_model import Lasso
lasso_regression = Lasso(alpha=0.1) # alpha — величина регуляризации

# обучение
lasso_regression.fit(X_train, y_train)

# вывод точности предсказания
print(lasso_regression.score(X_test, y_test))
print(lasso_regression.score(X_train, y_train))

0.1292291253603418
0.21638707543456437

In [ ]:
# Ridge регрессия
from sklearn.linear_model import Ridge
ridge_regression = Ridge(alpha=0.1) # alpha — величина регуляризации

# обучение
ridge_regression.fit(X_train, y_train)

# вывод точности предсказания
print(ridge_regression.score(X_test, y_test))
print(ridge_regression.score(X_train, y_train))

0.12921814439550416
0.2163870898198621

In [ ]:
# ElasticNet регрессия
from sklearn.linear_model import ElasticNet

elasticnet_regression = ElasticNet(alpha=0.1) # alpha — величина регуляризации

# обучение
elasticnet_regression.fit(X_train, y_train)

# вывод точности предсказания
print(elasticnet_regression.score(X_test, y_test))
print(elasticnet_regression.score(X_train, y_train))

0.1292307241070526
0.21638707330126183

In [ ]:
# Polynom регрессия
from sklearn.preprocessing import PolynomialFeatures 
from sklearn.linear_model import LinearRegression

for i in [2, 5, 10]:
  poly_regression= PolynomialFeatures(degree= i)  
  x_poly= poly_regression.fit_transform(X_train)  

  lin_reg =LinearRegression()  
  lin_reg.fit(x_poly, y_train)  

  print(lin_reg.score(x_poly, y_train))

0.24550279324088053
0.2819892076784609
0.3216800319415539